- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/elasticsearch-{{ elasticsearch_v }}.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/elasticsearch.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/elasticsearch_inst.sh {{ elasticsearch_v }}
