- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/elasticsearch_exporter-{{ elasticsearch_exporter_v }}.linux-amd64.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/elasticsearch_exporter.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/elasticsearch_exporter_inst.sh {{ elasticsearch_exporter_v }}
