- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/grafana-{{ grafana_v }}.linux-amd64.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/grafana.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/grafana_inst.sh {{ grafana_v }}
