- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/kafka_{{ kafka_v }}.tgz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/kafka.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/kafka_inst.sh {{ kafka_v }}
