- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/memcached_exporter-{{ memcached_exporter_v }}.linux-amd64.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/memcached_exporter.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/memcached_exporter_inst.sh {{ memcached_exporter_v }}
