- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/mysql-{{ mysql_v }}-linux-glibc2.12-x86_64.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/mysqld.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/mysql_inst.sh {{ mysql_v }}
