- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/nginx-vts-exporter-{{ nginx_vts_exporter_v }}.linux-amd64.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/nginx-vts-exporter.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/nginx-vts-exporter_inst.sh {{ nginx_vts_exporter_v }}
