- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/node_exporter-{{ node_exporter_v }}.linux-amd64.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/node_exporter.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/node_exporter_inst.sh {{ node_exporter_v }}
