- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/prometheus-{{ prometheus_v }}.linux-amd64.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/prometheus.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/prometheus_inst.sh {{ prometheus_v }}
