- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/redis_exporter-{{ redis_exporter_v }}.linux-amd64.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/redis_exporter.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/redis_exporter_inst.sh {{ redis_exporter_v }}
