- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/zabbix-{{ zabbix_v }}.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/zabbix-agent.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/zabbix-agent_inst.sh {{ zabbix_v }}
