- copy: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: '/usr/local/src/zookeeper-{{ zookeeper_v }}.tar.gz', dest: '/usr/local/src/' }
    - { src: '/usr/local/files/zookeeper.service', dest: '/usr/lib/systemd/system/' }
- script: /usr/local/scripts/zookeeper_inst.sh {{ zookeeper_v }}
